### ISSUE TITLE
Cannot read property `bind` of undefined

### ISSUE THREAD

**Issue by AaronHolbrook** [lkwdwrd/generator-vvv#52]
Was going through the `create` command and made it all the way to the `Advanced Customization Options` - I selected every option and was greeted with this `TypeError`:

```
? Advanced Customization Options (space bar to select, enter to continue): Customize Site Options, Add or Modify Constants, Add or Modify Environment Variables, Add static file p
roxies, Customize App Paths, Customize Composer Options
readline.js:925
            throw err;
            ^

TypeError: Cannot read property 'bind' of undefined
    at processAnswers (/Users/tyrun/dev/generator-vvv/lib/prompts/advanced-options.js:53:42)
    at wrapper (/Users/tyrun/dev/generator-vvv/node_modules/lodash/lodash.js:4405:19)
    at null.<anonymous> (/Users/tyrun/dev/generator-vvv/node_modules/yeoman-generator/lib/base.js:239:7)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:1489:14)
    at Subject.Rx.Subject.addProperties.onCompleted (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:5871:19)
    at Subject.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:63:31)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:5796:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:1489:14)
    at AutoDetachObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:63:31)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:5796:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:1489:14)
    at InnerObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:2966:65)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:63:31)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:5796:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/rx-lite/rx.lite.js:1489:14)
```

**Comment by AaronHolbrook** [comment]
Yup, confirmed that fixed the issue! I was able to successfully execute and modify all advanced options.
